name: docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag pavelmikhalchuk/keepalived_exporter:$(git rev-parse --short "$GITHUB_SHA")
      - name: Push the latest Docker image
        run: docker push pavelmikhalchuk/keepalived_exporter:latest
